services:
  soundboard-bot:
    container_name: soundboard-bot
    image: 'twongkk25/soundboard-bot:latest'
    volumes:
      - ./config:/usr/local/app/config
      - ./sounds:/usr/local/app/assets/sounds
    restart: unless-stopped
    
